name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm install --prefix backend

      - name: Run tests before deployment
        run: npm run test:all --prefix backend

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: './backend'

      - name: Set environment variables
        run: |
          az webapp config appsettings set \
            --resource-group smart-notes-rg-west \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --settings NODE_ENV=production JWT_SECRET=${{ secrets.JWT_SECRET }} FRONTEND_URL=https://smart-notes-app-lamb2025.azurewebsites.net DB_FILE=/tmp/notes_v2.db LOG_LEVEL=info JWT_EXPIRES_IN=24h

      - name: Restart web app
        run: az webapp restart --resource-group smart-notes-rg-west --name ${{ secrets.AZURE_WEBAPP_NAME }}

      - name: Health check
        run: |
          sleep 30
          curl -f https://smart-notes-app-lamb2025.azurewebsites.net/api/health || exit 1

